# Generated by Django 4.1.6 on 2023-03-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questmodel',
            old_name='ans',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='questmodel',
            name='op1',
        ),
        migrations.RemoveField(
            model_name='questmodel',
            name='op2',
        ),
        migrations.RemoveField(
            model_name='questmodel',
            name='op3',
        ),
        migrations.RemoveField(
            model_name='questmodel',
            name='op4',
        ),
    ]
