# Generated by Django 4.1.6 on 2023-03-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_ans_questmodel_answer_remove_questmodel_op1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questmodel',
            name='tried',
            field=models.BooleanField(default=False),
        ),
    ]
