# Generated by Django 4.1.2 on 2023-02-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='distributor_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='Courses'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='Lesson title', max_length=200),
        ),
    ]
