# Generated by Django 4.1.2 on 2023-02-06 23:16

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_distributor_name_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='Courses'),
        ),
    ]
