# Generated by Django 4.1.6 on 2023-03-08 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_questmodel_tried'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questmodel',
            name='tried',
        ),
        migrations.AddField(
            model_name='questmodel',
            name='tried_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.learner'),
        ),
    ]
