# Generated by Django 4.1.6 on 2023-03-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_questmodel_tried_questmodel_tried_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questmodel',
            name='tried_user',
        ),
    ]
