# Generated by Django 4.1.6 on 2023-02-09 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_user_email_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='occupation',
        ),
    ]
