# Generated by Django 4.1.6 on 2023-02-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_learner_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='social_link',
        ),
        migrations.AddField(
            model_name='user',
            name='social_link',
            field=models.URLField(default=''),
        ),
    ]
